# Site settings
title: Noel del Castillo
email: ngdelcastillo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Some memories of my code adventures.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://noeldelcastillo.me" # the base hostname & protocol for your site
twitter_username: ngdelcastillo
github_username:  ngdelcastillo

# Build settings
markdown: kramdown
